### ISSUE TITLE
Version 4.3 breaks Contact Layout Editor 1.2

### ISSUE THREAD

**Issue by clarkac1** [civicrm/org.civicrm.api4#105] opened 2019-03-07 09:15 UTC
## What happened:

1. @colemanw and @totten did a major refactor under-the-hood to apiv4. This did not change the api syntax, but **did** change the way a custom api should be implemented.
2. As api4 is still fairly new, the only extension to-date that implements a custom api is ContactLayout.
3. ContactLayout was updated to match the new structure and new versions of both extensions were published simultaneously.
4. That *should* have been fine, as typically when one runs extension upgrades one upgrades all extensions at once.
5. However, since the api4 extension is also bundled with core CiviCRM, this could result in one extension being upgraded before the other, as someone upgrades core but forgets to upgrade their extensions.

## What to do:

- At this point, there's probably not much to do other than warn people to upgrade extensions when upgrading core.
- A warning message in the 5.11 upgrade could have been helpful, to detect and disable older versions of CLE and alert the admin to install a new version.
- More robust dependency info would also be nice. Extensions can currently declare dependency on specific versions of core but not of other extensions.

Screenshot of broken CLE:
![screenshot_20190307_091123](https://user-images.githubusercontent.com/5676413/53945391-70605680-40b9-11e9-81f2-abd896682690.png)

**Comment by eileenmcnaughton** [comment] 2019-03-07 10:39
Contactlayouteditor 1.4.1 is compatabile with the latest apiv4 - so try upgrading that as well (it has been marked as needing CiviCRM 5.11 as that is the one that ships with the latest apiv4)

**Comment by clarkac1** [comment] 2019-03-07 11:08
Thanks for timely comment. So as it stands 4.3 is really incompatible with 5.10.4?  Or only if you have Contact Layout Editor?  If people see the update message & update as I did there are going to be lot of broken 5.10.x systems, aren't there?

**Comment by eileenmcnaughton** [comment] 2019-03-07 11:20
Right so there is a cross dependency between CSE 1.4.1 and API v 4.3 - so either upgrade neither or both. 

You can upgrade both on civi 5.10.4 (although 5.11 is out now & contains quite a few bug fixes since the security upgrade causes lots of people to upgrade, hence flushing out less frequent bugs).

We spotted this WRT the contact layout editor & changed the version it supports to 5.11 - which it the version that ships with the later api v4 release. We didn't spot that the api v4 needed to also  be 5.11+ to prevent the reverse mis-match

@colemanw @totten

**Comment by clarkac1** [comment] 2019-03-07 11:36
I think it would be better to close off this 5.10.x loophole somehow or others will fall down it as well as me (forgive the mixed metaphors).

**Comment by colemanw** [comment] 2019-03-07 18:10
I've updated this issue description to clarify exactly what happened.

**Comment by eileenmcnaughton** [comment] 2019-03-07 19:02
@colemanw I think you can prevent further instances by incrementing info.xml in the v4.3 api have version 5.11 - if people below that want to upgrade they can figure out the implications & do it but we should only advertise to 5.11 + sites

**Comment by colemanw** [comment] 2019-03-07 19:17
@eileenmcnaughton I saw that you and @totten bumped the version in info.xml last night. Unfortunately that doesn't help this specific situation because it is caused by loss of *backward* compatibility (and info.xml bumps only help with forward-compatibility issues). This is a very rare circumstance where upgrading one extension but not the other will cause breakage, because neither extensions' new version is backward compatible with an older version of the other.

I don't expect this sort of thing to happen again, because as api4 gets more popular we will need to avoid backward-incompatible changes like this one. There just wasn't a way to do this change well in a backward-compatible manner, and since CLE was the only extension that would break, and I could publish a new version of it simultaneously, I thought the disruption would be minimal and worth the benefits of the refactor.

**Comment by eileenmcnaughton** [comment] 2019-03-07 19:22
@colemanw right - but setting them both to version 5.11 should defacto set them to the same version as each other - ie. 5.10 sites won't upgrade apiv4 OR CSE if they don't see 'there is an upgrade available' & 5.11 sites WILL see the appropriate upgrade message - upgrade CSE

**Comment by colemanw** [comment] 2019-03-07 19:26
Unfortunately it's more complicated than that. Api4 is now bundled with core, so upgrading to CiviCRM 5.11 *automatically* upgrades api4 but *does not* automatically upgrade CLE, leaving unsuspecting admins with a broken system.

The fix would have been to add an upgrade routine prior to the release yesterday that checks for CLE and either automatically upgrades it or disables it with a message to the admin.

As of today, I'm not sure what to do. People should notice the break fairly quickly and hopefully think to upgrade their extensions...

**Comment by colemanw** [comment] 2019-03-07 19:29
I note that this problem only affects the 244 sites reported to use the CLE extension.

**Comment by eileenmcnaughton** [comment] 2019-03-07 19:30
@colemanw right - but the issue is we WANT 5.11 sites to upgrade CSE - which is advertised as an upgrade to them. 

We DON'T want to advertise the api upgrade to sites < 5.11 as it is LIKELY to cause them harm and UNLIKELY to provide any benefit - so re-releasing api 4.3 with a min civi version of 5.11 won't prevent that

**Closed** 2019-03-30 13:22 UTC
